{% set name = "openmm-atmmetaforce-plugin" %}
{% set version = "0.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Gallicchio-Lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fde821107efd4b47eed26c9eb9d07bff78ca219b3c13c796bc60253b3e61c3a1
  patches:
    - 0001-Fix-the-plugin-path.patch
    - 0002-Switch-to-setuptools.patch
    - 0003-Fix-setup.py-install.patch
    - 0004-Fix-OpenCL-linking.patch
    - 0005-Fix-for-SWIG-4.1.patch

build:
  number: 0
  skip: true  # [not linux64 and not win64]
  # Skip bronken OpenMM packages for Windows
  skip: true  # [win and py==38]
  skip: true  # [win and py==310]
  skip: true  # [cuda_compiler_version in (undefined, 'None')]
  rpaths:
    - lib/
    - lib/plugins/
  run_exports:
    # TODO: Relax max_pin at version 1.0 / stable API
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - make  # [linux]
    - ninja  # [win]
    - cmake
    - swig

  host:
    - openmm
    - python
    - setuptools

  run:
    # openmm package is missing a run_export as of 9 June 2022
    - {{ pin_compatible('openmm', min_pin='x.x', max_pin='x.x') }}
    - python

test:
  imports:
    - atmmetaforce

about:
  home: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin.git
  license: LGPL-2.0-only
  license_family: LGPL
  license_file:
    - LICENSE
  summary: The Alchemical Transfer Method Plugin for OpenMM
  description: |
    This plugin implements the Alchemical Transfer Potential (ATM) for the calculation
    of absolute and relative binding free energies of molecular complexes
    in OpenMM, a high performance toolkit for molecular simulation.
  doc_url: https://github.com/Gallicchio-Lab/async_re-openmm/tree/master/examples
  dev_url: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin.git

extra:
  recipe-maintainers:
    - egallicc
